# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Colene's Portfolio
email: cmcfarlane22@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the portfolio of Colene McFarlane. My site is still under construction -- please excuse the look.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://colene-m.github.io" # the base hostname & protocol for your site
github_username:  colene-m

# Build settings
markdown: kramdown
